import type { Contact } from "../types";

export const MOCK_CONTACTS: Contact[] = [
    {
        id: "1",
        company: "PharmaOne Ltd.",
        name: "Alice Johnson",
        email: "alice@pharmaone.com",
        phone: "+1234567890",
        country: "USA",
        city: "New York",
        department: "Procurement",
        designation: "Manager",
        industry: "Pharmaceuticals",
        companySize: "500-1000",
        lastContact: "2024-03-15",
        status: "Active"
    },
    {
        id: "2",
        company: "BioMed Inc.",
        name: "Bob Smith",
        email: "bob@biomed.com",
        phone: "+1987654321",
        country: "UK",
        city: "London",
        department: "Sales",
        designation: "Director",
        industry: "Biotechnology",
        companySize: "1000+",
        lastContact: "2024-03-10",
        status: "Active"
    },
    {
        id: "3",
        company: "MediCorp Solutions",
        name: "Carol White",
        email: "carol@medicorp.com",
        phone: "+1122334455",
        country: "Canada",
        city: "Toronto",
        department: "Research",
        designation: "Lead Scientist",
        industry: "Medical Devices",
        companySize: "100-500",
        lastContact: "2024-03-01",
        status: "Inactive"
    },
    {
        id: "4",
        company: "HealthTech Innovations",
        name: "David Brown",
        email: "david@healthtech.com",
        phone: "+1555666777",
        country: "Australia",
        city: "Sydney",
        department: "Product Development",
        designation: "VP",
        industry: "Healthcare Technology",
        companySize: "100-500",
        lastContact: "2024-03-12",
        status: "Active"
    },
    {
        id: "5",
        company: "PharmaTech Global",
        name: "Eva Martinez",
        email: "eva@pharmatech.com",
        phone: "+1777888999",
        country: "Spain",
        city: "Barcelona",
        department: "Marketing",
        designation: "Senior Manager",
        industry: "Pharmaceuticals",
        companySize: "1000+",
        lastContact: "2024-02-28",
        status: "Active"
    },
    {
        id: "6",
        company: "BioScience Labs",
        name: "Frank Wilson",
        email: "frank@bioscience.com",
        phone: "+1444555666",
        country: "Germany",
        city: "Berlin",
        department: "Operations",
        designation: "COO",
        industry: "Biotechnology",
        companySize: "500-1000",
        lastContact: "2024-03-05",
        status: "Inactive"
    },
    {
        id: "7",
        company: "MedEquip Solutions",
        name: "Grace Lee",
        email: "grace@medequip.com",
        phone: "+1333444555",
        country: "Singapore",
        city: "Singapore",
        department: "Procurement",
        designation: "Manager",
        industry: "Medical Equipment",
        companySize: "100-500",
        lastContact: "2024-03-08",
        status: "Active"
    },
    {
        id: "8",
        company: "LifeSciences Co",
        name: "Henry Chen",
        email: "henry@lifesciences.com",
        phone: "+1222333444",
        country: "China",
        city: "Shanghai",
        department: "Research",
        designation: "Research Director",
        industry: "Life Sciences",
        companySize: "1000+",
        lastContact: "2024-03-14",
        status: "Active"
    }
];
